# Generated by Django 5.2.8 on 2025-11-12 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Autor")),
                ("dataNascimento", models.DateField(verbose_name="Data de Nascimento")),
                (
                    "dataFalecimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Feminino"), ("M", "Masculino")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Editora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Editora")),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Gênero")),
            ],
        ),
        migrations.CreateModel(
            name="Linguagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Linguagem")),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.autor"
                    ),
                ),
                (
                    "editora",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.editora",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.genero",
                    ),
                ),
                (
                    "linguagem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.linguagem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("leitor", "Leitor"), ("admin", "Administrador")],
                        max_length=20,
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "fotoPerfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="perfil",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListaLeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.livro"
                    ),
                ),
                (
                    "leitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.perfil"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataEmprestimo", models.DateField(auto_now_add=True)),
                ("dataDevolução", models.DateField(verbose_name="Data de devolução")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("M", "Manutenção"),
                            ("D", "Disponível"),
                            ("E", "Emprestado"),
                            ("R", "Reservado"),
                        ],
                        default="M",
                        help_text="Status do Livro",
                        max_length=1,
                    ),
                ),
                ("devolvido", models.BooleanField(default=False)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="Empréstimo",
                        to="backend.livro",
                    ),
                ),
                (
                    "leitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="backend.perfil",
                    ),
                ),
            ],
        ),
    ]
